insert into dog (id, name, breed, origin) values (1, 'name 1', 'breed 1', 'origin 1')
insert into dog (id, name, breed, origin) values (2, 'name 2', 'breed 2', 'origin 2')
insert into dog (id, name, breed, origin) values (3, 'name 3', 'breed 3', 'origin 3')
insert into dog (id, name, breed, origin) values (4, 'name 4', 'breed 4', 'origin 4')
insert into dog (id, name, breed, origin) values (5, 'name 5', 'breed 5', 'origin 5')